[package]
name = "api"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
shared = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

actix-cors = "0.7.1"
actix-web = "4.12.1"

