[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
serde = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.11"
async-trait = "0.1"
